// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY7yuecPFAmosCm_2kC4fSHaPe6EotGZ0',
    appId: '1:971672420005:web:3960feba83fa6fa7aa574c',
    messagingSenderId: '971672420005',
    projectId: 'flutter-project-f1690',
    authDomain: 'flutter-project-f1690.firebaseapp.com',
    storageBucket: 'flutter-project-f1690.appspot.com',
    measurementId: 'G-XZ3HCP8SM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxBns7WmZcIIjgxIXL_rxfsmxzTUmjPmE',
    appId: '1:971672420005:android:c54d5c8079065875aa574c',
    messagingSenderId: '971672420005',
    projectId: 'flutter-project-f1690',
    storageBucket: 'flutter-project-f1690.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkQfNMhN5z2LbdLPWUTk9RO4ik_q_DK1c',
    appId: '1:971672420005:ios:4404c058ae6b9d2aaa574c',
    messagingSenderId: '971672420005',
    projectId: 'flutter-project-f1690',
    storageBucket: 'flutter-project-f1690.appspot.com',
    iosBundleId: 'com.example.toDoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkQfNMhN5z2LbdLPWUTk9RO4ik_q_DK1c',
    appId: '1:971672420005:ios:4404c058ae6b9d2aaa574c',
    messagingSenderId: '971672420005',
    projectId: 'flutter-project-f1690',
    storageBucket: 'flutter-project-f1690.appspot.com',
    iosBundleId: 'com.example.toDoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY7yuecPFAmosCm_2kC4fSHaPe6EotGZ0',
    appId: '1:971672420005:web:229169ab0cb1361daa574c',
    messagingSenderId: '971672420005',
    projectId: 'flutter-project-f1690',
    authDomain: 'flutter-project-f1690.firebaseapp.com',
    storageBucket: 'flutter-project-f1690.appspot.com',
    measurementId: 'G-45N9J3TEEV',
  );

}